# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Diff, filepath, HUnit, mtl, parsec, split, time
, utf8String, xml
}:

cabal.mkDerivation (self: {
  pname = "filestore";
  version = "0.6.0.3";
  src = ./.;
  buildDepends = [ Diff filepath parsec split time utf8String xml ];
  testDepends = [ Diff filepath HUnit mtl time ];
  meta = {
    description = "Interface for versioning file stores";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
