# This file was generated by `cabal2nix ./. > default.nix`,
# then edited to accept nixpkgs and devMode as arguments.

{ pkgs ? (import <nixpkgs> {}).pkgs
, devMode ? false
}:

let
  inherit (pkgs) haskellPackages;
  devDepends = if devMode
    then with pkgs; [
      git
      haskellPackages.cabalInstall
      less
      vim
    ]
    else [];

in with haskellPackages;
  cabal.mkDerivation (self: {
    pname = "filestore";
    version = "0.6.0.3";
    src = ./.;
    buildDepends = devDepends ++
      [ Diff filepath parsec split time utf8String xml ];
    testDepends = [ Diff filepath HUnit mtl time ];
    meta = {
      description = "Interface for versioning file stores";
      license = self.stdenv.lib.licenses.bsd3;
      platforms = self.ghc.meta.platforms;
    };
  })
